name: Deploy fib_erase
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_UP }} -p ${{ secrets.DOCKER_PW }}
      - run: docker build -t justin0979/fib_erase .
      - run: docker run -e CI=true justin0979/fib_erase npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'
